FOGL-7103: Modified to restart dispatcher service in case of SIGTERM s…
fledge-iot/fledge-service-dispatcher pull request #31
Opened 2022-12-05 13:33 UTC by gnandan

…ignal

Signed-off-by: nandan <nandan.ghildiyal@gmail.com>

2022-12-06 14:35 UTC, MarkRiddoch requested changes
The idea we discussed was to let the service stop, but just not unregister it. This way the core would restart it and we would have a fresh binary. As it is we have a problem because the core will send a SIGTERM to stop it if it does not respond to the API request to stop. Now we end up restarting it and would have a zombie server left behind.

2022-12-12 07:35 UTC, gnandan commented
> > The idea we discussed was to let the service stop, but just not unregister it. This way the core would restart it and we would have a fresh binary. As it is we have a problem because the core will send a SIGTERM to stop it if it does not respond to the API request to stop. Now we end up restarting it and would have a zombie server left behind.
> 
> Hi Mark Here I am not blocking service stop. when we call restart method it only set m_restartRequest = true and calls stop function to let the service stop. Flag m_restartRequest = true just not unregister the service when it's stopped.

Hi Mark,
I modified the code in a way that process doesn't call to internal restart. Instead it's just stopping service to get unregistered from core in case of SIGTERM signal, this way now process is getting restarted by the core.

2022-12-12 15:31 UTC, MarkRiddoch requested changes

2022-12-12 16:03 UTC, gnandan commented on C/services/dispatcher/dispatcher_service.cpp
> +void DispatcherService::stop(bool remvoeFromCore)
typo is fixed

2022-12-13 12:05 UTC, MarkRiddoch approved these changes

2022-12-13 12:13 UTC, merged